"""
Git hook installer.

Installs a Python post-commit hook that auto-mines staged .md files
and stages the resulting .st files. Cross-platform (Windows, Linux, macOS).

The hook reads OPENROUTER_API_KEY (or SMALLTALK_API_KEY) from the environment.
If neither is set, the hook prints a warning but exits cleanly — no commit is blocked.
"""
import stat
from pathlib import Path

from rich.console import Console

console = Console()

# The hook script embedded as a string so it ships without extra file dependencies.
_HOOK_SCRIPT = '''\
#!/usr/bin/env python3
"""
Smalltalk post-commit hook.

Auto-converts .md files that were part of this commit to .st format,
then stages the resulting .st files.

Requires: smalltalk-cli installed, OPENROUTER_API_KEY set in environment.
Generated by: smalltalk install-hook
"""
import os
import subprocess
import sys
from pathlib import Path


def main() -> None:
    api_key = os.environ.get("OPENROUTER_API_KEY") or os.environ.get("SMALLTALK_API_KEY")
    if not api_key:
        print("[smalltalk] No API key in environment — skipping auto-mine. "
              "Set OPENROUTER_API_KEY to enable.")
        return

    repo_root = Path(__file__).resolve().parent.parent.parent

    # Get files changed in the most recent commit
    try:
        result = subprocess.run(
            ["git", "diff-tree", "--no-commit-id", "-r", "--name-only", "HEAD"],
            capture_output=True, text=True, cwd=repo_root, check=True,
        )
        changed = result.stdout.strip().splitlines()
    except subprocess.CalledProcessError:
        return  # Not a valid commit context — skip silently

    md_files = [f for f in changed if f.endswith(".md")]
    if not md_files:
        return

    # Find unique parent directories
    dirs = sorted({str((repo_root / f).parent) for f in md_files})
    staged_st = []

    for d in dirs:
        target = Path(d)
        if not target.exists():
            continue

        r = subprocess.run(
            [sys.executable, "-m", "smalltalk.cli", "mine", str(target),
             "--api-key", api_key],
            capture_output=True, text=True, cwd=repo_root,
        )
        if r.returncode == 0:
            # Find .st files in this directory and stage them
            for st_file in target.rglob("*.st"):
                try:
                    rel = str(st_file.relative_to(repo_root))
                    staged_st.append(rel)
                except ValueError:
                    pass

    if staged_st:
        subprocess.run(["git", "add"] + staged_st, cwd=repo_root)
        print(f"[smalltalk] Auto-converted and staged {len(staged_st)} .st file(s).")


if __name__ == "__main__":
    main()
'''


def run_install_hook(project_dir: Path, force: bool = False) -> None:
    """
    Install the Smalltalk post-commit git hook.

    Args:
        project_dir: Root of the git repository (must contain .git/).
        force:       Overwrite an existing hook without prompting.
    """
    project_dir = project_dir.resolve()
    git_dir     = project_dir / ".git"

    if not git_dir.is_dir():
        console.print(f"[red]ERROR:[/red] Not a git repository: {project_dir}")
        console.print("  Run `git init` first, or point to the repo root.")
        raise SystemExit(1)

    hooks_dir = git_dir / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)

    hook_path = hooks_dir / "post-commit"

    if hook_path.exists() and not force:
        console.print(f"[yellow]⚠[/yellow] Hook already exists: {hook_path}")
        console.print("  Use [bold]--force[/bold] to overwrite.")
        raise SystemExit(1)

    hook_path.write_text(_HOOK_SCRIPT, encoding="utf-8")

    # Mark executable on Unix-like systems
    try:
        current = hook_path.stat().st_mode
        hook_path.chmod(current | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    except (OSError, AttributeError):
        pass  # Windows — execution controlled by shebang / caller

    console.print(f"[green]✓[/green] Hook installed: {hook_path}")
    console.print()
    console.print("  On every [bold]git commit[/bold], staged .md files will be auto-converted")
    console.print("  to .st format and staged in the same commit.")
    console.print()
    console.print("  [bold]Requirement:[/bold] set [cyan]OPENROUTER_API_KEY[/cyan] in your shell profile.")
    console.print("  Without it the hook exits cleanly — commits are never blocked.")
    console.print()
    console.print("  To uninstall: delete the hook file:")
    console.print(f"    {hook_path}")
